export 'package:login/views/home/index.dart';
export 'package:login/views/layout/index.dart';
export 'package:login/views/login/login.dart';
export 'package:login/views/login/loginB.dart';
export 'package:login/views/login/newPageA.dart';
export 'package:login/views/login/newPageB.dart';
export 'package:login/views/pluss/index.dart';
export 'package:login/views/user/index.dart';
export 'package:login/componets/menu/index.dart';
